### ISSUE TITLE
Prompt user about prerequisite completion

### ISSUE THREAD

**Issue by KrashLeviathan** [hammer-io/tyr#33]
When a user starts `hammer-cli` for the first time, it asks a series of questions about some prerequisite steps that must be taken. Mostly account creation stuff.

When it starts, maybe it asks, "Do you have a GitHub account to use?" If they answer "No", then it refers them to the appropriate website to create an account. If they answer "Yes", it saves the "Yes to GitHub" answer to a config file (`~/.hammer-cli/config` or something) so that it never asks them that question again.

### Example:

```
$ hammer-cli my-new-project
Do you have a GitHub account to use? (y/N)
$ no
GitHub will be used as the code repository for your project. Please
visit https://github.com/ and create an account.
[exit]
$ hammer-cli my-new-project
Do you have a GitHub account to use? (y/N)
$ yes
Project name: 
...
[later, they create another project]
$ hammer-cli some-other-project
Project name:
... [it didn't ask them again]
```

### TravisCI or other optionals

If they choose TravisCI, docker, or some other optional thing, it asks them whether or not they created an account for that service. If they didn't, it will halt the process without generating the project. If they say "Yes", it again saves that information in the config file so it doesn't ask again later.

### Subtasks

- [x] Figure out how to generate a local config file when `npm install -g` is run on a user's machine
- [ ] Ask about GitHub account if config file says they haven't answered YES yet
- [ ] Ask about TravisCI account if config file says they haven't answered YES yet
- [ ] Ask about Dockerhub account if config file says they haven't answered YES yet
- [ ] For any question that answers YES, update the config file
- [ ] For any question that answers NO, advise them what to do next and exit without continuing

**Comment by jackcmeyer** [comment]
https://www.npmjs.com/package/preferences

This would be a good way to store these preferences. 

Apparently they can be encrypted as well, so would be good for storing username, passwords, and tokens, but we should look into the validity of the encryption.
